AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
     ImageId: ami-0e6329e222e662a52
     InstanceType: t2.micro
     KeyName: !Ref KeyPair
     AvailabilityZone: ap-south-1a
     SecurityGroups:
       - !Ref MySecurityGroup
     Tags:
     - Key: Name
       Value: Swadhin
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol : tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
  KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: newkeypair