AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e6329e222e662a52
      AvailabilityZone: ap-south-1a
      KeyName: !Ref KeyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
      SecurityGroups:
        - !Ref EC2SG
    DependsOn:
      - EC2SG
  KeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: veeresh
  EC2SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22' 
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        